### ISSUE TITLE
LCD support

### ISSUE THREAD

**Issue by mdaffin** [WiringPi/WiringPi-Python-Deprecated#11]
There is currently no support for the wiringpi [LCD library](https://projects.drogon.net/raspberry-pi/wiringpi/lcd-library/).

It would be nice to be able to use LCD screens with this python module.

**Comment by Gadgetoid** [comment]
Adding this into WiringPi2 now. Little late, but better late than never! Alas, I don't have an LCD to test it with, so I'd appreciate someone stepping in and giving it a go.

**Comment by Gadgetoid** [comment]
LCD support added to WiringPi2-1.0.7. https://github.com/WiringPi/WiringPi2-Python
