### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by rst-** [WiringPi/WiringPi-Python-Deprecated#13]
In addition to python-dev, the installation seems to require setuptools:

**_@**_**\* ~/projects/WiringPi-Python $ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages, Extension
ImportError: No module named setuptools

So, please add step:

sudo apt-get install python-setuptools

**Comment by tdingman** [comment]
Ran into the same error. Thanks for the help!
