### ISSUE TITLE
Can you push this to PyPI?

### ISSUE THREAD

**Issue by skorokithakis** [WiringPi/WiringPi-Python-Deprecated#16]
It would be useful if this were pushed to PyPI as `wiringpi`.

**Comment by Bengt** [comment]
Yes, having this on the PyPI would be great. It is the way to go with Python packaging.

**Comment by Gadgetoid** [comment]
See WiringPi2 on Pypi!

https://pypi.python.org/pypi/wiringpi2

Also, WiringPi _is_ on Pypi?

https://pypi.python.org/pypi/wiringpi

**Comment by skorokithakis** [comment]
Oh, thanks for that, `pip install wiringpi` didn't work on my Raspberry Pi for some reason, and I couldn't find it on PyPI. Ticket closed, then!
