### ISSUE TITLE
Import Error with Python 3

### ISSUE THREAD

**Issue by Bengt** [WiringPi/WiringPi-Python-Deprecated#21]
I just installed the current version using Git as described in the README. Additionally, I installed using pip-3.2:

With Python 2, import works as expected:

```
$ python
>>> import wiringpi
>>> 
```

With Python3 however, it fails:

```
$ python3
>>> import wiringpi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.2/dist-packages/wiringpi-1.1.0-py3.2-linux-armv6l.egg/wiringpi.py", line 26, in <module>
    _wiringpi = swig_import_helper()
  File "/usr/local/lib/python3.2/dist-packages/wiringpi-1.1.0-py3.2-linux-armv6l.egg/wiringpi.py", line 22, in swig_import_helper
    _mod = imp.load_module('_wiringpi', fp, pathname, description)
ImportError: /usr/local/lib/python3.2/dist-packages/wiringpi-1.1.0-py3.2-linux-armv6l.egg/_wiringpi.cpython-32mu.so: undefined symbol: PyInt_FromSize_t
>>> 
```

When running as root, I get another error:

```
$ sudo su
$ python3
>>> import wiringpi
Traceback (most recent call last):
  File "wiringpi.py", line 16, in swig_import_helper
    fp, pathname, description = imp.find_module('_wiringpi', [dirname(__file__)])
ImportError: No module named _wiringpi

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wiringpi.py", line 26, in <module>
    _wiringpi = swig_import_helper()
  File "wiringpi.py", line 18, in swig_import_helper
    import _wiringpi
ImportError: /usr/local/lib/python3.2/dist-packages/wiringpi-1.1.0-py3.2-linux-armv6l.egg/_wiringpi.cpython-32mu.so: undefined symbol: PyInt_FromSize_t
>>> 
```

**Comment by Gadgetoid** [comment]
Please try WiringPi2-Python and let me know how you get on:

https://github.com/Gadgetoid/WiringPi2-Python

**Comment by Bengt** [comment]
On my Pi installation and import of WiringPi2-Python works as described in the corresponding README with Python 2.7.3 and Python 3.2.3.

**Comment by Gadgetoid** [comment]
Brilliant! Thanks for taking the time to let me know. Consider WiringPi2-Python the official replacement for WiringPi-Python. I don't think it would be worth spending any more time bringing WiringPi-Python up to scratch and will likely just be replacing it.

WiringPi2-Python isn't actually all that much different conceptually, it's based upon Gordon's WiringPi 2.x, which has some awesome new features you can read about here: http://wiringpi.com

Can I consider this bug closed?

**Comment by Bengt** [comment]
You are welcome. Thanks for building these handy wrappers.

As you say it's not worth fixing, a close as won't-fix would be appropriate. That would but apply to all the issues in this repository. Would you consider it the right time to shift-over the focus of development to WiringPi2-Python? If so, the READMEs should state that, I think.

**Comment by Gadgetoid** [comment]
Updated the README, will probably make it more explicit. Also Forked WiringPi2-Python into the WiringPi org, as I now consider it "stable," mainly because it's currently far, far better than WiringPi-Python.
