### ISSUE TITLE
Add missing functions to GPIO class

### ISSUE THREAD

**Issue by Tuckie** [WiringPi/WiringPi-Python-Deprecated#6]
softPwmCreate, softPwmWrite, wiringPiSPISetup, etc...

Thank you for all your work work on this!

**Comment by andig** [comment]
waitForInterrupt would be highly appreciated

**Comment by Gadgetoid** [comment]
Now maintaining these in WiringPi2-Python! A belated thanks for your kind words. I've found that maintaining a library such as this is often a thankless chore, but I feel duty-bound to come back with a vengeance after my 7-month absence, and knowing people use/care about this library is reassuring!

See: wiringPiSPIDataRW
