### ISSUE TITLE
Support for Interrupts

### ISSUE THREAD

**Issue by pacmac** [WiringPi/WiringPi-Python-Deprecated#8]
Hi, would it be possible to add the support for interrupts i.e. waitForInterrupt()

**Comment by Gadgetoid** [comment]
I will try and get WiringPi updated with the latest functionality as soon as possible. I realise I've been neglecting it somewhat due to time constraints, but should have the opportunity to rectify that soon.

**Comment by andig** [comment]
Would love to see the interrupts- thank you!

**Comment by andig** [comment]
Latest MagPi edition had an article on GPIO with interrupts

**Comment by andig** [comment]
Would love to see it.

**Comment by Gadgetoid** [comment]
Interrupt support has been added to WiringPi2-Python, but I'm not sure if it will work. This is something I need to test, as I don't fully understand how interrupts are implemented.

Presumably a call to "WaitForInterrupt" will hang the program thread until an interrupt is triggered; so you'd have to cope with this accordingly.

See: https://github.com/WiringPi/WiringPi2-Python

waitForInterrupt( PIN, WAIT_FOR_MILLISECONDS )
